export enum ModelType {
  App = 'APP',
  Auth = 'AUTH',
  Grid = 'GRID',
  Container = 'CONTAINER',
  Element = 'ELEMENT',
  Workflow = 'WORKFLOW',
  Component = 'COMPONENT',
  Action = 'ACTION',
  Event = 'EVENT',
  Model = 'MODEL',
  Field = 'FIELD',
  Content = 'CONTENT',
  Page = 'PAGE',
  Global = 'GLOBAL',
}

export enum Auth {
  Register = 'REGISTER',
  Login = 'LOGIN',
}

export enum ModalIDs {
  Testing = 'TESTING',
  AddNode = 'ADD_NODE',
  LoginRegister = 'LOGIN_REGISTER',
  Register = 'REGISTER',
  Login = 'LOGIN',
  VerifyAccount = 'VERIFY_ACCOUNT',
  ForgotPassword = 'FORGOT_PASSWORD',
  ConfirmForgotPassword = 'CONFIRM_FORGOT_PASSWORD',
  AppUpdate = 'APP_UPDATE',
  AppCreate = 'APP_CREATE',
  ModelCreate = 'MODEL_CREATE',
  ModelEdit = 'MODEL_EDIT',
  ModelAddField = 'MODEL_ADD_FIELD',
  ModelEditField = 'MODEL_EDIT_FIELD',
  ContentCreate = 'CONTENT_CREATE',
  ContentEdit = 'CONTENT_EDIT',
  ContainerCreate = 'CONTAINER_CREATE',
  GridCreate = 'GRID_CREATE',
  ConfigGridCreate = 'CONFIGGRID_CREATE',
  GridUpdate = 'GRID_UPDATE',
  ElementCreate = 'ELEMENT_CREATE',
  ElementUpdate = 'ELEMENT_UPDATE',
  GlobalCreate = 'GLOBALCONFIG_CREATE',
  GlobalUpdate = 'GLOBAL_UPDATE',
  PageUpdate = 'PAGE_UPDATE',
  PageCreate = 'PAGE_CREATE',
  ConfigComponentCreate = 'CONFIGCOMPONENT_CREATE',
}
