/**
 * ################################
 * DO NOT EDIT, GENERATED BY YEOMAN
 * ################################
 */
const path = require('path');
const webpack = require('webpack');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const PACKAGE_DIRS = [
  'style',
  'utils',
  'component',
  'system',
  'next-apollo',
  'layout',
];

/**
 * Map package names to their respective dist file location.
 *
 * 'form/dist/main.bundle': path.resolve(__dirname, 'form/index.ts'),
 */
const entry = PACKAGE_DIRS.reduce((acc, dir) => {
  acc[`${dir}`] = path.resolve(__dirname, `${dir}/index.ts`);
  return acc;
}, {});

/**
 * ['form/dist', 'form/__generated']
 */
const cleanOnceBeforeBuildPatterns = PACKAGE_DIRS.reduce((acc, dir) => {
  return acc.concat([`${dir}/dist`, `${dir}/__generated__`]);
}, []);

/**
 * Map all path for module resolution
 * [
 *   path.resolve(__dirname, 'form'),
 *   path.resolve(__dirname, 'form/node_modules'),
 *   // Lerna installs shared packages in project root upstream
 *   path.resolve(__dirname, '../node_modules'),
 * ],
 */
const modules = PACKAGE_DIRS.reduce(
  (acc, dir) => {
    acc.unshift(path.resolve(__dirname, `${dir}/node_modules`));
    acc.unshift(path.resolve(__dirname, `${dir}`));
    return acc;
  },
  [path.resolve(__dirname, '../node_modules')],
);

module.exports = {
  mode: 'development',
  entry,
  target: 'node',
  devtool: 'source-map',
  output: {
    path: path.resolve(__dirname),
    library: ['@codelab', '[name]'],
    libraryTarget: 'umd',
    filename: '[name]/dist/main.bundle.js',
    devtoolNamespace: '@codelab',
    devtoolModuleFilenameTemplate: info => {
      for (var i = 0; i < PACKAGE_DIRS.length; i++) {
        const dir = PACKAGE_DIRS[i];
        if (info.resourcePath.includes(`packages/${dir}/`)) {
          return `webpack:///${info.namespace}/${dir}/${info.resourcePath}?${
            info.allLoaders
          }`;
        }
      }
      return `webpack:///${info.namespace}/${info.resourcePath}?${
        info.allLoaders
      }`;
    },
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: { loader: 'babel-loader' },
      },
      // Namespace not supported by babel-loader, need ts-loader to handle
      // typescript files
      {
        test: /\.tsx?$/,
        exclude: /node_modules/,
        loader: 'ts-loader',
        options: {
          configFile: 'tsconfig.webpack.json',
        },
      },
      { enforce: 'pre', test: /\.js$/, loader: 'source-map-loader' },
      {
        test: /\.(sa|sc|c)ss$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
      },
    ],
  },
  plugins: [
    // new CleanWebpackPlugin({
    //   cleanOnceBeforeBuildPatterns,
    // }),
    new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output
      // both options are optional
      filename: '[name]/dist/main.bundle.css',
      chunkFilename: '[id].css',
    }),
    // SourceMap fix for Typescript
    // https://github.com/webpack/webpack/issues/7172
    // new webpack.SourceMapDevToolPlugin({
    //   filename: '[file].map',
    //   exclude: [/.*node_modules.*/],
    //   // namespace: ['@codelab', '[name]'],
    //   moduleFilenameTemplate:
    // 'webpack://[namespace]/[resource-path]?[loaders]', }),
  ],
  resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
    modules,
  },
  externals: [
    'styled-components',
    'emotion-theming',
    '@emotion/core',
    'react',
    'react-dom',
    'antd',
    'formik',
    'yup',
  ],
};
